// React/src/components/TreeViewPlain.tsx
import { useCallback, useRef } from 'react';
import TreeView from 'devextreme-react/tree-view';
import Sortable from 'devextreme-react/sortable';
import dxTreeView, { type Node, type Item as TreeItem } from 'devextreme/ui/tree_view';
import { type SortableTypes } from 'devextreme-react/sortable';
import { itemsDrivePlain as plainData } from '../data';

interface TreeFieldExpr {
  key: string;
  parentKey: string;
}

interface TreeViewPlainProps {
  shouldClearSelection: boolean;
}

function draggedItemsRender(data: SortableTypes.DragTemplateData): JSX.Element {
  const draggedItems = data.itemData.map((node: Node) => <div key={node.text} className='dragged-item'>{node.text}</div>);
  return (<div>{draggedItems}</div>);
}

function isParent(node: Node, possibleParentNode: Node): boolean {
  if (!node.parent) return false;
  return node.parent.key !== possibleParentNode.key ? isParent(node.parent, possibleParentNode) : true;
}

function getTopNodes(nodes: Node[]): Node[] {
  return nodes.filter((nodeToCheck: Node) => !nodes.some((n: Node) => isParent(nodeToCheck, n)));
}

function getNodeByKey(nodes: Node[], key: string | number | null): Node | null {
  for (const node of nodes) {
    if (node.key === key) {
      return node;
    }
    if (node.children) {
      const foundNode = getNodeByKey(node.children, key);
      if (foundNode != null) {
        return foundNode;
      }
    }
  }
  return null;
}

function getVisualIndexByNode(treeView: dxTreeView, key: string | number): number {
  const nodeElements = Array.from(treeView.element().querySelectorAll('.dx-treeview-node'));
  const nodeElement = nodeElements.find((n: Element) => n.getAttribute('data-item-id') === key);
  return nodeElements.indexOf(nodeElement as Element);
}

function getNodeByVisualIndex(treeView: dxTreeView, index: number): Node | null {
  const nodeElement = treeView.element().querySelectorAll('.dx-treeview-node')[index];
  if (nodeElement) {
    return getNodeByKey(treeView.getNodes(), nodeElement.getAttribute('data-item-id'));
  }
  return null;
}

function getLocalIndex(array: TreeItem[], key: string | number, keyExpr: string): number {
  const idsArray = array.map((elem: TreeItem) => (elem as Record<string, unknown>)[keyExpr] as string | number);
  return idsArray.indexOf(key);
}

function calculateToIndex(e: SortableTypes.DragChangeEvent | SortableTypes.DragEndEvent): number {
  if (e.dropInsideItem) return e.toIndex ?? 0;
  const fromIndex = e.fromIndex ?? 0;
  const toIndex = e.toIndex ?? 0;
  return fromIndex >= toIndex ? toIndex : toIndex + 1;
}

function canDrag(treeView: dxTreeView, e: SortableTypes.DragStartEvent): boolean {
  const fromNode = getNodeByVisualIndex(treeView, e.fromIndex);
  return !!(fromNode?.selected && e.itemData?.length);
}

function canDrop(treeView: dxTreeView, e: SortableTypes.DragChangeEvent | SortableTypes.DragEndEvent, toNode: Node | null): boolean {
  if (!toNode) return false;
  const canAcceptChildren = (e.dropInsideItem && toNode.itemData && toNode.itemData.hasItems) || !e.dropInsideItem;
  const toNodeIsChild = toNode && e.itemData.some((i: Node) => isParent(toNode, i));
  const fromIndices = e.itemData.map((i: Node) => getVisualIndexByNode(treeView, i.key));
  const targetThemselves = toNode && (e.itemData.some((i: Node) => i.key === toNode.key) || fromIndices.includes(e.toIndex));
  return canAcceptChildren && !toNodeIsChild && !targetThemselves;
}

function moveNodes(items: TreeItem[], e: SortableTypes.DragEndEvent, toNode: Node | null, treeFieldExpr: TreeFieldExpr): void {
  const nodesToMove = getTopNodes(e.itemData);
  const fromIndices = nodesToMove.map((i: Node) => getLocalIndex(items, i.key, treeFieldExpr.key)).reverse();
  fromIndices.forEach((i: number) => items.splice(i, 1));
  const toIndex = toNode === null || !toNode.itemData
    ? items.length
    : getLocalIndex(items, (toNode.itemData as Record<string, unknown>)[treeFieldExpr.key] as string | number, treeFieldExpr.key);
  items.splice(toIndex, 0, ...nodesToMove.map((i: Node) => i.itemData as TreeItem).filter((item): item is TreeItem => item !== undefined));
  nodesToMove.forEach((i: Node) => {
    if (i.itemData && toNode?.itemData) {
      if (e.dropInsideItem) {
        (i.itemData as Record<string, unknown>)[treeFieldExpr.parentKey] = (toNode.itemData as Record<string, unknown>)[treeFieldExpr.key];
      } else {
        (i.itemData as Record<string, unknown>)[treeFieldExpr.parentKey] = toNode != null ? (toNode.itemData as Record<string, unknown>)[treeFieldExpr.parentKey] : undefined;
      }
    }
  });
}

function TreeViewPlain(props: TreeViewPlainProps): JSX.Element {
  const treeViewRef = useRef<dxTreeView>(null);

  const dragStart = useCallback((e: SortableTypes.DragStartEvent) => {
    const treeView = treeViewRef.current?.instance();
    if (!treeView) return;
    e.itemData = treeView.getSelectedNodes();
    e.cancel = !canDrag(treeView, e);
  }, []);

  const dragChange = useCallback((e: SortableTypes.DragChangeEvent) => {
    const treeView = treeViewRef.current?.instance();
    if (!treeView) return;
    const toNode = getNodeByVisualIndex(treeView, calculateToIndex(e));
    e.cancel = !canDrop(treeView, e, toNode);
  }, []);

  const dragEnd = useCallback((e: SortableTypes.DragEndEvent) => {
    const treeView = treeViewRef.current?.instance();
    if (!treeView) return;
    const toNode = getNodeByVisualIndex(treeView, calculateToIndex(e));
    const allItems = treeView.option('items') as TreeItem[];
    const treeViewExpr = {
      key: treeView.option('keyExpr') as string,
      parentKey: treeView.option('parentIdExpr') as string,
    };
    if (canDrop(treeView, e, toNode)) {
      moveNodes(allItems, e, toNode, treeViewExpr);
    }
    treeView.option('items', allItems);
    if (props.shouldClearSelection) {
      treeView.unselectAll();
    }
  }, [props.shouldClearSelection]);

  return (
    <Sortable filter='.dx-treeview-item'
      allowDropInsideItem={true}
      allowReordering={true}
      onDragStart={dragStart}
      onDragChange={dragChange}
      onDragEnd={dragEnd}
      dragRender={draggedItemsRender}
    >
      <TreeView ref={treeViewRef}
        items={plainData}
        className='tab-item-content'
        expandNodesRecursive={false}
        selectNodesRecursive={false}
        showCheckBoxesMode='normal'
        dataStructure='plain'
        displayExpr='name'
        width={300}
      ></TreeView>
    </Sortable>
  );
}

export default TreeViewPlain;

// Angular/src/app/components/tree-view-plain/tree-view-plain.component.ts
import { Component, ViewChild, Input } from '@angular/core';
import { CommonModule } from '@angular/common';
import { DataService } from 'src/app/services/data.service';
import { DxSortableModule, DxTreeViewComponent, DxTreeViewModule } from 'devextreme-angular';
import { DxSortableTypes } from 'devextreme-angular/ui/sortable';
import dxTreeView, { Node, Item as TreeItem } from 'devextreme/ui/tree_view';

interface TreeFieldExpr {
  key: string;
  parentKey: string;
}

@Component({
  selector: 'tree-view-plain',
  templateUrl: './tree-view-plain.component.html',
  standalone: true,
  imports: [CommonModule, DxTreeViewModule, DxSortableModule],
})
export class TreeViewPlainComponent {
  @ViewChild('treeView') treeView!: DxTreeViewComponent;

  @Input() shouldClearSelection = false;

  treeItems: TreeItem[];

  constructor(dataService: DataService) {
    this.treeItems = dataService.getPlainData();
    this.dragStart = this.dragStart.bind(this);
    this.dragChange = this.dragChange.bind(this);
    this.dragEnd = this.dragEnd.bind(this);
  }

  dragStart(e: DxSortableTypes.DragStartEvent): void {
    const treeView = this.treeView.instance;
    e.itemData = treeView.getSelectedNodes();
    e.cancel = !this.canDrag(treeView, e);
  }

  dragChange(e: DxSortableTypes.DragChangeEvent): void {
    const treeView = this.treeView.instance;
    const toNode = this.getNodeByVisualIndex(treeView, this.calculateToIndex(e));
    e.cancel = !this.canDrop(treeView, e, toNode);
  }

  dragEnd(e: DxSortableTypes.DragEndEvent): void {
    const treeView = this.treeView.instance;
    const toNode = this.getNodeByVisualIndex(treeView, this.calculateToIndex(e));
    const allItems = treeView.option('items') as TreeItem[];
    if (!allItems) return;
    const treeViewExpr = {
      key: treeView.option('keyExpr') as string,
      parentKey: treeView.option('parentIdExpr') as string,
    };
    if (this.canDrop(treeView, e, toNode)) {
      this.moveNodes(allItems, e, toNode, treeViewExpr);
    }
    treeView.option('items', allItems);
    if (this.shouldClearSelection) {
      treeView.unselectAll();
    }
  }

  canDrag(treeView: dxTreeView, e: DxSortableTypes.DragStartEvent): boolean {
    const fromNode = this.getNodeByVisualIndex(treeView, e.fromIndex ?? 0);
    return !!(fromNode?.selected && e.itemData?.length);
  }

  canDrop(treeView: dxTreeView, e: DxSortableTypes.DragChangeEvent | DxSortableTypes.DragEndEvent, toNode: Node | null): boolean {
    if (!toNode) return false;
    const canAcceptChildren = (e.dropInsideItem && toNode.itemData && toNode.itemData.hasItems) || !e.dropInsideItem;
    const toNodeIsChild = toNode && e.itemData.some((i: Node) => this.isParent(toNode, i));
    const fromIndices = e.itemData.map((i: Node) => this.getVisualIndexByKey(treeView, i.key));
    const targetThemselves = toNode && (e.itemData.some((i: Node) => i.key === toNode.key) || fromIndices.includes(e.toIndex ?? 0));
    return canAcceptChildren && !toNodeIsChild && !targetThemselves;
  }

  moveNodes(items: TreeItem[], e: DxSortableTypes.DragEndEvent, toNode: Node | null, treeFieldExpr: TreeFieldExpr): void {
    const nodesToMove = this.getTopNodes(e.itemData as Node[]);
    const fromIndices = nodesToMove.map((i: Node) => this.getLocalIndex(items, i.key, treeFieldExpr.key)).reverse();
    fromIndices.forEach((i: number) => items.splice(i, 1));
    const toIndex = toNode === null || !toNode.itemData
      ? items.length
      : this.getLocalIndex(items, (toNode.itemData as Record<string, unknown>)[treeFieldExpr.key] as string | number, treeFieldExpr.key);
    items.splice(toIndex, 0, ...nodesToMove.map((i: Node) => i.itemData).filter((item): item is TreeItem => item !== undefined));
    nodesToMove.forEach((i: Node) => {
      if (i.itemData && toNode?.itemData) {
        if (e.dropInsideItem) {
          (i.itemData as Record<string, unknown>)[treeFieldExpr.parentKey] = (toNode.itemData as Record<string, unknown>)[treeFieldExpr.key];
        } else {
          (i.itemData as Record<string, unknown>)[treeFieldExpr.parentKey] = toNode != null ? (toNode.itemData as Record<string, unknown>)[treeFieldExpr.parentKey] : undefined;
        }
      }
    });
  }

  isParent(node: Node, possibleParentNode: Node): boolean {
    if (!node.parent) return false;
    return node.parent.key !== possibleParentNode.key ? this.isParent(node.parent, possibleParentNode) : true;
  }

  getTopNodes(nodes: Node[]): Node[] {
    return nodes.filter((nodeToCheck: Node) => !nodes.some((n: Node) => this.isParent(nodeToCheck, n)));
  }

  getVisualIndexByKey(treeView: dxTreeView, key: string | number): number {
    const nodeElements = Array.from(treeView.element().querySelectorAll('.dx-treeview-node'));
    const nodeElement = nodeElements.find((n: Element) => n.getAttribute('data-item-id') === String(key));
    return nodeElements.indexOf(nodeElement as Element);
  }

  getNodeByVisualIndex(treeView: dxTreeView, index: number): Node | null {
    const nodeElement = treeView.element().querySelectorAll('.dx-treeview-node')[index];
    if (nodeElement) {
      return this.getNodeByKey(treeView.getNodes() as Node[], nodeElement.getAttribute('data-item-id'));
    }
    return null;
  }

  getNodeByKey(nodes: Node[], key: string | number | null): Node | null {
    for (const node of nodes) {
      if (node.key === key) {
        return node;
      }
      if (node.children) {
        const foundNode = this.getNodeByKey(node.children, key);
        if (foundNode != null) {
          return foundNode;
        }
      }
    }
    return null;
  }

  getLocalIndex(array: TreeItem[], key: string | number, keyExpr: string): number {
    const idsArray = array.map((elem: TreeItem) => (elem as Record<string, unknown>)[keyExpr] as string | number);
    return idsArray.indexOf(key);
  }

  calculateToIndex(e: DxSortableTypes.DragChangeEvent | DxSortableTypes.DragEndEvent): number {
    if (e.dropInsideItem) return e.toIndex ?? 0;
    const fromIndex = e.fromIndex ?? 0;
    const toIndex = e.toIndex ?? 0;
    return fromIndex >= toIndex ? toIndex : toIndex + 1;
  }
}

<dx-sortable filter=".dx-treeview-item"
    [allowDropInsideItem]="true"
    [allowReordering]="true"
    (onDragStart)="dragStart($event)"
    (onDragChange)="dragChange($event)"
    (onDragEnd)="dragEnd($event)"
    dragTemplate="draggedItemsTemplate"
    >
    <div *dxTemplate="let dragData of 'draggedItemsTemplate'">
        <div *ngFor="let node of dragData.itemData">
            <div class="dragged-item">{{node.text}}</div>
        </div>
    </div>
    <dx-tree-view #treeView
        class="tab-item-content"
        [items]="treeItems"
        [expandNodesRecursive]="false"
        [selectNodesRecursive]="false"
        showCheckBoxesMode="normal"
        dataStructure="plain"
        displayExpr="name"
        [width]="300"
    ></dx-tree-view>
</dx-sortable>
