// Angular/src/app/components/tree-view-plain/tree-view-plain.component.ts
import { Component, ViewChild, Input } from '@angular/core';
import { DataService } from 'src/app/services/data.service';
import { DxTreeViewComponent } from 'devextreme-angular';

@Component({
  selector: 'tree-view-plain',
  templateUrl: './tree-view-plain.component.html'
})
export class TreeViewPlainComponent {
    @ViewChild("treeView") treeView: DxTreeViewComponent;
    @Input() shouldClearSelection: boolean;
    treeItems: any[];
    constructor(dataService: DataService) {
        this.treeItems = dataService.getPlainData();
        this.dragStart = this.dragStart.bind(this);
        this.dragChange = this.dragChange.bind(this);
        this.dragEnd = this.dragEnd.bind(this);
    }
    dragStart(e) {
        const treeView = this.treeView.instance;
        e.itemData = treeView.getSelectedNodes();
        e.cancel = !this.canDrag(treeView, e);
    }
    dragChange(e) {
        const treeView = this.treeView.instance;
        const allItems = treeView.option("items");
        const toNode = this.getNodeByVisualIndex(treeView, this.calculateToIndex(e));
        e.cancel = !this.canDrop(allItems, e, toNode, treeView.option("keyExpr"));
    }
    dragEnd(e) {
        const treeView = this.treeView.instance;
        const toNode = this.getNodeByVisualIndex(treeView, this.calculateToIndex(e));
        const allItems = treeView.option("items");
        const treeViewExpr = {
            items: treeView.option("itemsExpr"),
            key: treeView.option("keyExpr"),
            parentKey: treeView.option("parentIdExpr")
        }
        if (this.canDrop(allItems, e, toNode, treeViewExpr.key)) {
            this.moveNodes(allItems, e, toNode, treeViewExpr);
        }
        treeView.option("items", allItems);
        if (this.shouldClearSelection)
            treeView.unselectAll();
    }
    canDrag(treeView, e) {
        const fromNode = this.getNodeByVisualIndex(treeView, e.fromIndex);
        return fromNode.selected && e.itemData && e.itemData.length;
    }
    canDrop(items, e, toNode, keyExpr) {
        const canAcceptChildren = (e.dropInsideItem && toNode.itemData.isDirectory) || !e.dropInsideItem;
        const toNodeIsChild = toNode && e.itemData.some(i => this.isParent(toNode, i));
        const fromIndices = e.itemData.map(i => this.getLocalIndex(items, i.key, keyExpr));
        const targetThemselves = toNode && (e.itemData.some(i => i.key === toNode.key) || fromIndices.includes(e.toIndex));
        return canAcceptChildren && !toNodeIsChild && !targetThemselves;
    }
    moveNodes(items, e, toNode, treeFieldExpr) {
        const nodesToMove = this.getTopNodes(e.itemData);
        const fromIndices = nodesToMove.map(i => this.getLocalIndex(items, i.key, treeFieldExpr.key)).reverse();
        fromIndices.forEach(i => items.splice(i, 1));
        const toIndex = toNode === null
            ? items.length
            : this.getLocalIndex(items, toNode.itemData[treeFieldExpr.key], treeFieldExpr.key);
        items.splice(toIndex, 0, ...nodesToMove.map(i => i.itemData));
        nodesToMove.forEach(i => {
            if (e.dropInsideItem) {
                i.itemData[treeFieldExpr.parentKey] = toNode.itemData[treeFieldExpr.key];
            } else {
                i.itemData[treeFieldExpr.parentKey] = toNode != null ? toNode.itemData[treeFieldExpr.parentKey] : undefined;
            }
        });
    }
    isParent(node, possibleParentNode) {
        if (!node.parent) return false;
        return node.parent.key !== possibleParentNode.key ? this.isParent(node.parent, possibleParentNode) : true;
    }
    getTopNodes(nodes) {
        return nodes.filter(nodeToCheck => {
            return !nodes.some(n => this.isParent(nodeToCheck, n));
        });
    }
    getNodeByVisualIndex(treeView, index) {
        const nodeElement = treeView.element().querySelectorAll('.dx-treeview-node')[index];
        if (nodeElement) {
            return this.getNodeByKey(treeView.getNodes(), nodeElement.getAttribute('data-item-id'));
        }
        return null;
    }
    getNodeByKey(nodes, key) {
        for (let i = 0; i < nodes.length; i++) {
            if (nodes[i].key == key) {
                return nodes[i];
            }
            if (nodes[i].children) {
                const node = this.getNodeByKey(nodes[i].children, key);
                if (node != null) {
                    return node;
                }
            }
        }
        return null;
    }
    getLocalIndex(array, key, keyExpr) {
        const idsArray = array.map((elem) => elem[keyExpr]);
        return idsArray.indexOf(key);
    }
    calculateToIndex(e) {
        if (e.dropInsideItem) return e.toIndex;
        return e.fromIndex >= e.toIndex ? e.toIndex : e.toIndex + 1;
    }
}

<dx-sortable filter=".dx-treeview-item"
    [allowDropInsideItem]="true"
    [allowReordering]="true"
    (onDragStart)="dragStart($event)"
    (onDragChange)="dragChange($event)"
    (onDragEnd)="dragEnd($event)"
    dragTemplate="draggedItemsTemplate"
    >
    <div *dxTemplate="let dragData of 'draggedItemsTemplate'">
        <div *ngFor="let node of dragData.itemData">
            <div class="dragged-item">{{node.text}}</div>
        </div>
    </div>
    <dx-tree-view #treeView
        class="tab-item-content"
        [items]="treeItems"
        [expandNodesRecursive]="false"
        [selectNodesRecursive]="false"
        showCheckBoxesMode="normal"
        dataStructure="plain"
        displayExpr="name"
        [width]="300"
    ></dx-tree-view>
</dx-sortable>

// React/src/TreeViewPlain.js
import { useCallback, useRef } from 'react';
import TreeView from 'devextreme-react/tree-view';
import Sortable from 'devextreme-react/sortable';
import { plainData } from './data';

function draggedItemsRender(data) {
    const draggedItems = data.itemData.map((node) => 
        <div key={node.text} className="dragged-item">{node.text}</div>
    );
    return (<div>{draggedItems}</div>);
}

function canDrag(treeView, e) {
    const fromNode = getNodeByVisualIndex(treeView, e.fromIndex);
    return fromNode.selected && e.itemData && e.itemData.length;
}
function canDrop(items, e, toNode, keyExpr) {
    const canAcceptChildren = (e.dropInsideItem && toNode.itemData.isDirectory) || !e.dropInsideItem;
    const toNodeIsChild = toNode && e.itemData.some(i => isParent(toNode, i));
    const fromIndices = e.itemData.map(i => getLocalIndex(items, i.key, keyExpr));
    const targetThemselves = toNode && (e.itemData.some(i => i.key === toNode.key) || fromIndices.includes(e.toIndex));
    return canAcceptChildren && !toNodeIsChild && !targetThemselves;
}
function moveNodes(items, e, toNode, treeFieldExpr) {
    const nodesToMove = getTopNodes(e.itemData);
    const fromIndices = nodesToMove.map(i => getLocalIndex(items, i.key, treeFieldExpr.key)).reverse();
    fromIndices.forEach(i => items.splice(i, 1));
    const toIndex = toNode === null
        ? items.length
        : getLocalIndex(items, toNode.itemData[treeFieldExpr.key], treeFieldExpr.key);
    items.splice(toIndex, 0, ...nodesToMove.map(i => i.itemData));
    nodesToMove.forEach(i => {
        if (e.dropInsideItem) {
            i.itemData[treeFieldExpr.parentKey] = toNode.itemData[treeFieldExpr.key];
        } else {
            i.itemData[treeFieldExpr.parentKey] = toNode != null ? toNode.itemData[treeFieldExpr.parentKey] : undefined;
        }
    });
}
function isParent(node, possibleParentNode) {
    if (!node.parent) return false;
    return node.parent.key !== possibleParentNode.key ? isParent(node.parent, possibleParentNode) : true;
}
function getTopNodes(nodes) {
    return nodes.filter(nodeToCheck => {
        return !nodes.some(n => isParent(nodeToCheck, n));
    });
}
function getNodeByVisualIndex(treeView, index) {
    const nodeElement = treeView.element().querySelectorAll('.dx-treeview-node')[index];
    if (nodeElement) {
        return getNodeByKey(treeView.getNodes(), nodeElement.getAttribute('data-item-id'));
    }
    return null;
}
function getNodeByKey(nodes, key) {
    for (let i = 0; i < nodes.length; i++) {
        if (nodes[i].key == key) {
            return nodes[i];
        }
        if (nodes[i].children) {
            const node = getNodeByKey(nodes[i].children, key);
            if (node != null) {
                return node;
            }
        }
    }
    return null;
}
function getLocalIndex(array, key, keyExpr) {
    const idsArray = array.map((elem) => elem[keyExpr]);
    return idsArray.indexOf(key);
}
function calculateToIndex(e) {
    if (e.dropInsideItem) return e.toIndex;
    return e.fromIndex >= e.toIndex ? e.toIndex : e.toIndex + 1;
}

function TreeViewPlain(props) {
    const treeViewRef = useRef(null);

    const dragStart = useCallback((e) => {
        const treeView = treeViewRef.current.instance;
        e.itemData = treeView.getSelectedNodes();
        e.cancel = !canDrag(treeView, e);
    }, []);
    const dragChange = useCallback((e) => {
        const treeView = treeViewRef.current.instance;
        const allItems = treeView.option("items");
        const toNode = getNodeByVisualIndex(treeView, calculateToIndex(e));
        e.cancel = !canDrop(allItems, e, toNode, treeView.option("keyExpr"));
    }, []);
    const dragEnd = useCallback((e) => {
        const treeView = treeViewRef.current.instance;
        const toNode = getNodeByVisualIndex(treeView, calculateToIndex(e));
        const allItems = treeView.option("items");
        const treeViewExpr = {
            items: treeView.option("itemsExpr"),
            key: treeView.option("keyExpr"),
            parentKey: treeView.option("parentIdExpr")
        }
        if (canDrop(allItems, e, toNode, treeViewExpr.key)) {
            moveNodes(allItems, e, toNode, treeViewExpr);
        }
        treeView.option("items", allItems);
        if (props.shouldClearSelection)
            treeView.unselectAll();
    }, [props.shouldClearSelection]);
    

  return (
    <Sortable filter=".dx-treeview-item"
        allowDropInsideItem={true}
        allowReordering={true}
        onDragStart={dragStart}
        onDragChange={dragChange}
        onDragEnd={dragEnd}
        dragRender={draggedItemsRender}
    >
        <TreeView ref={treeViewRef}
            items={plainData}
            className="tab-item-content"
            expandNodesRecursive={false}
            selectNodesRecursive={false}
            showCheckBoxesMode="normal"
            dataStructure="plain"
            displayExpr="name"
            width={300}
        ></TreeView>
    </Sortable>
  );
}

export default TreeViewPlain;
